# CMake generated Testfile for 
# Source directory: /Users/cys/embedded/lv_port_pc_vscode
# Build directory: /Users/cys/embedded/lv_port_pc_vscode/build-local
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(fruit_ninja_assets_test "/Users/cys/embedded/lv_port_pc_vscode/bin/fruit_ninja_assets_test")
set_tests_properties(fruit_ninja_assets_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;506;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(fruit_ninja_collision_test "/Users/cys/embedded/lv_port_pc_vscode/bin/fruit_ninja_collision_test")
set_tests_properties(fruit_ninja_collision_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;512;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(fruit_ninja_model_test "/Users/cys/embedded/lv_port_pc_vscode/bin/fruit_ninja_model_test")
set_tests_properties(fruit_ninja_model_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;518;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(design_fruit_model_test "/Users/cys/embedded/lv_port_pc_vscode/bin/design_fruit_model_test")
set_tests_properties(design_fruit_model_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;524;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(desktop_apple_music_test "/Users/cys/embedded/lv_port_pc_vscode/bin/desktop_apple_music_test")
set_tests_properties(desktop_apple_music_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;530;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(tetris_public_api_test "/Users/cys/embedded/lv_port_pc_vscode/bin/tetris_public_api_test")
set_tests_properties(tetris_public_api_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;536;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(v9_2048_core_test "/Users/cys/embedded/lv_port_pc_vscode/bin/v9_2048_core_test")
set_tests_properties(v9_2048_core_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;542;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(v9_2048_public_api_test "/Users/cys/embedded/lv_port_pc_vscode/bin/v9_2048_public_api_test")
set_tests_properties(v9_2048_public_api_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;548;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_data_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_data_test")
set_tests_properties(apple_music_data_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;554;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_desktop_file_dialog_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_desktop_file_dialog_test")
set_tests_properties(apple_music_desktop_file_dialog_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;560;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_state_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_state_test")
set_tests_properties(apple_music_state_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;566;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(desktop_apple_music_launcher_test "/Users/cys/embedded/lv_port_pc_vscode/bin/desktop_apple_music_launcher_test")
set_tests_properties(desktop_apple_music_launcher_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;572;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(desktop_runtime_page_count_test "/Users/cys/embedded/lv_port_pc_vscode/bin/desktop_runtime_page_count_test")
set_tests_properties(desktop_runtime_page_count_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;578;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_parent_size_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_parent_size_test")
set_tests_properties(apple_music_parent_size_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;584;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_now_view_state_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_now_view_state_test")
set_tests_properties(apple_music_now_view_state_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;590;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_now_view_single_file_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_now_view_single_file_test")
set_tests_properties(apple_music_now_view_single_file_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;596;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_playlist_popup_layout_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_playlist_popup_layout_test")
set_tests_properties(apple_music_playlist_popup_layout_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;602;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_playlist_scrollbar_behavior_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_playlist_scrollbar_behavior_test")
set_tests_properties(apple_music_playlist_scrollbar_behavior_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;608;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
add_test(apple_music_single_file_player_test "/Users/cys/embedded/lv_port_pc_vscode/bin/apple_music_single_file_player_test")
set_tests_properties(apple_music_single_file_player_test PROPERTIES  WORKING_DIRECTORY "/Users/cys/embedded/lv_port_pc_vscode" _BACKTRACE_TRIPLES "/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;614;add_test;/Users/cys/embedded/lv_port_pc_vscode/CMakeLists.txt;0;")
subdirs("third-party/hls_player_demo/src/http_client")
subdirs("third-party/hls_player_demo/src/player_controller")
subdirs("third-party/hls_player_demo/src/stream_player")
subdirs("lvgl")
