#ifndef ICON_REPLACE_2_LAYOUT_H
#define ICON_REPLACE_2_LAYOUT_H

#define SCREEN_W 800
#define SCREEN_H 480
#define PAGE_WIDTH SCREEN_W
#define PAGE_HEIGHT SCREEN_H
#define TOP_BAR_H 40
#define DESKTOP_W SCREEN_W
#define DESKTOP_H (SCREEN_H - TOP_BAR_H)

#define ICON_START_X 90
#define ICON_START_Y 50
#define ICON_MAX_ROW 3
#define ICON_MAX_COL 5
#define ICON_X_DISTANCE 140
#define ICON_Y_DISTANCE 140
#define ICON_SIZE 60

#define PAGE_COUNT 3
#define ICON_SLOT_COUNT (ICON_MAX_ROW * ICON_MAX_COL)

#endif
