# CMake generated Testfile for 
# Source directory: /home/share/samba/lvgl/lv_port_pc_vscode_flyingcys
# Build directory: /home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/build-codex
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(fruit_ninja_assets_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/fruit_ninja_assets_test")
set_tests_properties(fruit_ninja_assets_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;537;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(fruit_ninja_collision_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/fruit_ninja_collision_test")
set_tests_properties(fruit_ninja_collision_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;543;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(fruit_ninja_model_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/fruit_ninja_model_test")
set_tests_properties(fruit_ninja_model_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;549;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(design_fruit_model_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/design_fruit_model_test")
set_tests_properties(design_fruit_model_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;555;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(desktop_apple_music_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/desktop_apple_music_test")
set_tests_properties(desktop_apple_music_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;561;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(tetris_public_api_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/tetris_public_api_test")
set_tests_properties(tetris_public_api_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;567;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(v9_2048_core_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/v9_2048_core_test")
set_tests_properties(v9_2048_core_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;573;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(v9_2048_public_api_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/v9_2048_public_api_test")
set_tests_properties(v9_2048_public_api_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;579;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_data_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_data_test")
set_tests_properties(apple_music_data_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;585;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_desktop_file_dialog_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_desktop_file_dialog_test")
set_tests_properties(apple_music_desktop_file_dialog_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;591;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_state_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_state_test")
set_tests_properties(apple_music_state_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;597;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(desktop_apple_music_launcher_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/desktop_apple_music_launcher_test")
set_tests_properties(desktop_apple_music_launcher_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;603;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(desktop_runtime_page_count_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/desktop_runtime_page_count_test")
set_tests_properties(desktop_runtime_page_count_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;609;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(desktop_vertical_swipe_lock_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/desktop_vertical_swipe_lock_test")
set_tests_properties(desktop_vertical_swipe_lock_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;615;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_parent_size_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_parent_size_test")
set_tests_properties(apple_music_parent_size_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;621;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_now_view_state_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_now_view_state_test")
set_tests_properties(apple_music_now_view_state_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;627;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_now_view_single_file_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_now_view_single_file_test")
set_tests_properties(apple_music_now_view_single_file_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;633;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_playlist_popup_layout_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_playlist_popup_layout_test")
set_tests_properties(apple_music_playlist_popup_layout_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;639;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_playlist_scrollbar_behavior_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_playlist_scrollbar_behavior_test")
set_tests_properties(apple_music_playlist_scrollbar_behavior_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;645;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
add_test(apple_music_single_file_player_test "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/bin/apple_music_single_file_player_test")
set_tests_properties(apple_music_single_file_player_test PROPERTIES  WORKING_DIRECTORY "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys" _BACKTRACE_TRIPLES "/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;651;add_test;/home/share/samba/lvgl/lv_port_pc_vscode_flyingcys/CMakeLists.txt;0;")
subdirs("third-party/hls_player_demo/src/http_client")
subdirs("third-party/hls_player_demo/src/player_controller")
subdirs("third-party/hls_player_demo/src/stream_player")
subdirs("lvgl")
